### PR TITLE
use the v3 version of the deps.dev API

### PR DESCRIPTION
**Pull request by josieang**
While we (deps.dev) try to minimize breaking changes to v3alpha, it is experimental and will change from time to time. For stability, let's use the v3 API which does have stability guarantees (https://blog.deps.dev/api-v3/).

### CODE REVIEW

**Review by jhutchings1 — APPROVED** [review]

**Comment by juxtin** [comment]
Thanks for doing this, @josieang! This PR is currently failing in CI because it needs to be rebuilt, would you mind running `npm run all` and committing the result?

**Comment by josieang** [comment]
Thanks! This should be done.

**Review by juxtin — APPROVED** [review]

**Comment by juxtin** [comment]
Hi @josieang, somehow we've ended up with a conflict in `dist/index.js.map`. Would you mind updating this PR from main and then running `npm run all` again?

**Comment by josieang** [comment]
Just done. Thanks.

**Comment by josieang** [comment]
I've just updated it to main and I ran `npm run all` again. however I don't have permission to merge, @juxtin would you be able to merge this?

**Comment by josieang** [comment]
Apologies, I realise now I'm supposd to run `npm install` before running `npm run build && np run package`. Got a diff.

**Pull request merged**
