### PR TITLE
Update action to node20

### PR DESCRIPTION
**Pull request by takost**
**Description:**
Node 16 has reached end-of-life on 11 Sep 202.
This PR updates the default runtime to node20, rather then node16.

This is supported on all Actions Runners [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

### CODE REVIEW

**Comment by takost** [comment]
@febuiles Could you please help me to test it properly? I am not sure how to reproduce that problem with proxy, so not sure about testing. Also I think we can release new major version of this action, for other first party actions we released new major versions after node change

**Comment by febuiles** [comment]
@takost Apologies for the delay getting back to you, I was out visiting family.

In order to test the changes, we need to setup a self-hosted runner (can be done on your local machine) and the add the  HTTPS proxy in front of it. (`nc` and `stunnel` should do the job, or something like `nginx` if you already have that installed).

> I think we can release new major version of this action, for other first party actions we released new major versions after node change

Let's do this. Do you mind bumping it in this PR? We can get this merged so you have confirmation that `main` is running Node 20. I can perform the testing somewhere in the next two weeks and update the docs to point to `v4`

**Comment by takost** [comment]
@febuiles I tested the PR with proxy behind runner, and my workflow passed.

**Review by febuiles — APPROVED** [review]
@takost thank you very much!

**Pull request merged**
