### PR TITLE
Add Feature: Write Summary as comment to the pull request

### PR DESCRIPTION
**Pull request by davelosert**
This Pull-Requests adds the feature to also put the summary of the dependency review as a comment into a pull-request. This makes it easier and more intuitive to surface the information.

To be backwards-compatible, it is turned off by default and can be turned on via an action-input.

A live example of how it looks like can be seen in [this pull request in davelosert/action-test-repository](https://github.com/davelosert/action-test-repository):

dependency review comment

If permissions are missing, a warning is printed as can be seen in [this workflow run in davelosert/action-test-repository](https://github.com/davelosert/action-test-repository/actions/runs/4084088300):
dependency review warning

I wasn't sure if I should write any tests for the `comment-pr.ts`-file, as it would involve mostly mocking the octokit-library. Happy to do it on request. 🙂

### CODE REVIEW

**Comment by febuiles** [comment]
Thanks, this looks pretty cool! I'll try to test things out and merge before end of week.

**Comment by febuiles** [comment]
@courtneycl will wait on feedback before merging this.

**Comment by davelosert** [comment]
@febuiles , @courtneycl : Any update on this?
I can fix the merge conflicts as soon as you give me a green light. 🙂

**Comment by courtneycl** [comment]
Hi @davelosert! Thanks so much for this contribution, having greater visibility in the summary is great. 

I think this is okay to merge as-is since it's a configuration option. I'd like to modify the format of the summary file to be more compact--it's really quite large when used as a comment--but I won't get to that in the immediate future and don't want to stand in the way of folks using this in the mean time if they're okay with the sizeable comment. 🤓

**Comment by febuiles** [comment]
Merging as is. I understand that a few changes in the comment formatting are coming in another PR so I'll hold on releasing a new version until this is fully fleshed out.

**Pull request merged**
